name: dorsal_stream
modality: video
batch_size: 32
model_name: simple3d7
num_epochs: 15
learning_rate: 0.001
smooth_weight: 0.00001
weight_decay: 0.00001
lr_decay_step: 10
lr_decay_gamma: 0.1
endtoend: True
layers: 
    - none
stimulus_sizes: 
    - 64
encoding_ckpt: dorsal_stream_simple3d7
