name: dorsal_stream
modality: video
batch_size: 64
model_name: dorsalnet
num_epochs: 15
learning_rate: 0.001
smooth_weight: 0.0001
weight_decay: 0.0001
lr_decay_step: 10
lr_decay_gamma: 0.1
layers: 
    - s1
    - res0
    - res1
    - res2
stimulus_sizes: 
    - 112 
    - 224
encoding_ckpt: dorsal_stream_dorsalnet
