name: dorsal_stream
stimulus_size: 32
model_name: linear
lpips_weight: 0
batch_size: 64
num_epochs: 25
learning_rate: 0.001
weight_decay: 0
lr_decay_step: 20
lr_decay_gamma: 0.1
early_stopping: True
patience: 5
num_neurons: 315
neuron_ablation: True
baseline: True
ckpt_dir: './checkpoints/dorsal_stream/linear/'
