name: ventral_stream
stimulus_size: 32
model_name: cnn
lpips_weight: 0
batch_size: 64
num_epochs: 25
learning_rate: 0.001
weight_decay: 0
lr_decay_step: 20
lr_decay_gamma: 0.1
early_stopping: True
patience: 2
ckpt_dir: './checkpoints/ventral_stream/cnn/'